# Generated by Django 6.0.2 on 2026-04-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="articles",
            field=models.ManyToManyField(
                blank=True, related_name="newsletters", to="news_app.article"
            ),
        ),
    ]
