# Generated by Django 6.0.2 on 2026-05-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0002_newsletter_articles"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="poster_type",
            field=models.CharField(
                choices=[
                    ("journalist", "Independent Journalist"),
                    ("publisher", "Publisher-Branded"),
                ],
                default="journalist",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
