# Generated by Django 6.0.2 on 2026-05-05 03:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0003_article_poster_type_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-01-01"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="publisher",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="subscribed_journalists",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscribers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
