# Generated by Django 6.0.2 on 2026-05-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "news_app",
            "0004_publisher_date_created_publisher_is_verified_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
