# Generated by Django 6.0.2 on 2026-05-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0005_user_bio_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="article_images/"
            ),
        ),
    ]
