# Generated by Django 6.0.2 on 2026-05-18 09:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0007_article_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
